import type { IPreset } from '../model/types'

export const PRESETS: IPreset[] = [
	{
		baseMax: 16,
		baseMin: 16,
		gridStep: 4,
		i18nNameKey: 'presets.classic',
		id: 'classic',
		intermediateSteps: 4,
		ratioMax: 2,
		shouldSnapToGrid: false,
	},
	{
		baseMax: 16,
		baseMin: 16,
		gridStep: 4,
		i18nNameKey: 'presets.geist',
		id: 'geist',
		intermediateSteps: 2,
		ratioMax: 1.5,
		shouldSnapToGrid: true,
	},
	{
		baseMax: 14,
		baseMin: 17,
		gridStep: 4,
		i18nNameKey: 'presets.spectrum',
		id: 'spectrum',
		intermediateSteps: 0,
		ratioMax: 1.125,
		ratioMin: 1.125,
		shouldSnapToGrid: false,
	},
	{
		baseMax: 14,
		baseMin: 14,
		gridStep: 4,
		i18nNameKey: 'presets.polaris',
		id: 'polaris',
		intermediateSteps: 0,
		ratioMax: 1.2,
		shouldSnapToGrid: true,
	},
	{
		baseMax: 20,
		baseMin: 16,
		gridStep: 4,
		i18nNameKey: 'presets.musicalTrinonic',
		id: 'musicalTrinonic',
		intermediateSteps: 2,
		ratioMax: 2,
		shouldSnapToGrid: false,
	},
	{
		baseMax: 20,
		baseMin: 16,
		gridStep: 4,
		i18nNameKey: 'presets.musicalTetratonic',
		id: 'musicalTetratonic',
		intermediateSteps: 3,
		ratioMax: 2,
		shouldSnapToGrid: false,
	},
	{
		baseMax: 20,
		baseMin: 18,
		gridStep: 4,
		i18nNameKey: 'presets.majorThird',
		id: 'majorThird',
		intermediateSteps: 0,
		ratioMax: 1.25,
		shouldSnapToGrid: true,
	},
]
