name: Vue-TSC

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check-types:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6

      - name: Setup pnpm and Node.js
        uses: pnpm/setup@v2
        with:
          cache: true
          runtime: node@26.8.2

      - name: Run Vue‑TSC
        run: pnpm run check:types
