name: Vitest

on:
  push:
    branches: [main, develop]
    paths:
      - 'app/**/*'
      - 'layers/**/*'
      - '.node-version'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - 'vitest.config.ts'
      - 'nuxt.config.ts'
  pull_request:
    branches: [main, develop]
    paths:
      - 'app/**/*'
      - 'layers/**/*'
      - '.node-version'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - 'vitest.config.ts'
      - 'nuxt.config.ts'

jobs:
  test-runtime:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup pnpm and Node.js
        uses: pnpm/setup@v2
        with:
          cache: true
          runtime: node@26.8.2

      - name: Run runtime tests
        run: pnpm test --run --reporter=verbose
